// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf4UG1LKLQ2itlfK2FeZMdJ7v4W5pwwJo',
    appId: '1:325981656242:web:e3cc879c155fcb276b65ab',
    messagingSenderId: '325981656242',
    projectId: 'chat-app-64108',
    authDomain: 'chat-app-64108.firebaseapp.com',
    storageBucket: 'chat-app-64108.appspot.com',
    measurementId: 'G-06WSC6JETX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARGQvAaqygdnh25_eM0-BFAtALtRGq_AU',
    appId: '1:325981656242:android:a0b37b59b72118ae6b65ab',
    messagingSenderId: '325981656242',
    projectId: 'chat-app-64108',
    storageBucket: 'chat-app-64108.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4za4eHRXGIXkVKcAhJFbCblKQOJ_fdbM',
    appId: '1:325981656242:ios:f2516da00b220cfc6b65ab',
    messagingSenderId: '325981656242',
    projectId: 'chat-app-64108',
    storageBucket: 'chat-app-64108.appspot.com',
    iosClientId: '325981656242-o6r7m0uhe7oguscf8qcu2oclh09k2jb2.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4za4eHRXGIXkVKcAhJFbCblKQOJ_fdbM',
    appId: '1:325981656242:ios:f2516da00b220cfc6b65ab',
    messagingSenderId: '325981656242',
    projectId: 'chat-app-64108',
    storageBucket: 'chat-app-64108.appspot.com',
    iosClientId: '325981656242-o6r7m0uhe7oguscf8qcu2oclh09k2jb2.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  //windows
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARGQvAaqygdnh25_eM0-BFAtALtRGq_AU',
    appId: '1:325981656242:android:a0b37b59b72118ae6b65ab',
    messagingSenderId: '325981656242',
    projectId: 'chat-app-64108',
    // storageBucket: 'chat-app-64108.appspot.com',
  );
}
